//Copyright (c) 2021 Heewon Cho

#ifndef _CERIUM_NET_PROTOCOL_OPCODE
#define _CERIUM_NET_PROTOCOL_OPCODE

#define CERIUM_PACKET_TYPE_VERSION 0x0000
#define CERIUM_PACKET_TYPE_VERACK 0x0001
#define CERIUM_PACKET_TYPE_GETADDR 0x0002
#define CERIUM_PACKET_TYPE_ADDR 0x0003

#endif