//Copyright (c) 2021 Heewon Cho

#ifndef _CERIUM_NET_PROTOCOL_PACKETTYPES
#define _CERIUM_NET_PROTOCOL_PACKETTYPES

#define CERIUM_PACKET_TYPE_VERSION 0x0000
#define CERIUM_PACKET_TYPE_VERACK 0x0001

#endif